server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  loadbalancer:
    enabled: on
    clients:
      client:
        health-check:
          interval: 30s
      compte:
        health-check:
          interval: 30s
  application:
    name: composite
